#pragma once

#include <cstdint>

enum class CastleRights : uint8_t {
  NO_CASTLE = 0,
  WHITE_KINGSIDE = 1 << 0,
  WHITE_QUEENSIDE = 1 << 1,
  BLACK_KINGSIDE = 1 << 2,
  BLACK_QUEENSIDE = 1 << 3,

  WHITE_CASTLING = WHITE_KINGSIDE | WHITE_QUEENSIDE,
  BLACK_CASTLING = BLACK_KINGSIDE | BLACK_QUEENSIDE,
  ALL_CASTLING = WHITE_CASTLING | BLACK_CASTLING,
};
